services:
  - type: web
    name: veyra-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ESEWA_MERCHANT_CODE
        sync: false
      - key: ESEWA_SECRET_KEY
        sync: false
      - key: KHALTI_SECRET_KEY
        sync: false
