services:
  - type: web
    name: sajilomarts-backend
    runtime: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://pratikshah2056_db_user:Ajita_777@cluster0.hvnskf.mongodb.net/sajilomarts?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGO_URI
        value: mongodb+srv://pratikshah2056_db_user:Ajita_777@cluster0.hvnskf.mongodb.net/sajilomarts?retryWrites=true&w=majority&appName=Cluster0
      - key: ADMIN_EMAIL
        value: pratikshah2990@gmail.com
      - key: ADMIN_PASSWORD
        value: Ajit@777
      - key: INDIA_NPR_CONVERSION_RATE
        value: "1.65"
      - key: SERVICE_CHARGE_PERCENT
        value: "20"
      - key: DELIVERY_CHARGE_NPR
        value: "200"
