services:
  - type: web
    name: sajilomarts-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: NEXT_PUBLIC_GEMINI_ENABLED
        value: "true"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: "veyra-np"
      - key: FIREBASE_CLIENT_EMAIL
        value: "firebase-adminsdk-fbsvc@veyra-np.iam.gserviceaccount.com"
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: INDIA_SOURCE_PIN
        value: "854341"
      - key: INDIA_NPR_CONVERSION_RATE
        value: "1.65"
      - key: SERVICE_CHARGE_PERCENT
        value: "20"
      - key: DELIVERY_CHARGE_NPR
        value: "200"
      - key: ESEWA_MERCHANT_CODE
        sync: false
      - key: ESEWA_SECRET_KEY
        sync: false
      - key: KHALTI_SECRET_KEY
        sync: false
