services:
  - type: web
    name: sajilomarts-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: INDIA_NPR_CONVERSION_RATE
        value: "1.65"
      - key: SERVICE_CHARGE_PERCENT
        value: "20"
      - key: DELIVERY_CHARGE_NPR
        value: "200"
