import { Category, Product } from "@/lib/types";

export const categories: Category[] = [
  { id: "fashion", name: "Fashion", description: "Modern apparel and daily wear picks.", image: "https://images.unsplash.com/photo-1483985988355-763728e1935b" },
  { id: "footwear", name: "Footwear", description: "Sneakers, shoes and all-day comfort styles.", image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff" },
  { id: "watches", name: "Watches", description: "Smart, classic and lifestyle timepieces.", image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30" },
  { id: "bags", name: "Bags", description: "Travel, work and everyday carry choices.", image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa" },
  { id: "accessories", name: "Accessories", description: "Belts, wallets, sunglasses and more.", image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518" },
  { id: "beauty-lifestyle", name: "Beauty & Lifestyle", description: "Useful personal and lifestyle products.", image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9" },
  { id: "mobile-accessories", name: "Mobile Accessories", description: "Cases, chargers and phone essentials.", image: "https://images.unsplash.com/photo-1601593346740-925612772716" },
  { id: "tech-gadgets", name: "Tech & Gadgets", description: "Earbuds, speakers, devices and accessories.", image: "https://images.unsplash.com/photo-1518444065439-e933c06ce9cd" },
  { id: "everyday-essentials", name: "Everyday Essentials", description: "Compact daily-use essentials for home and travel.", image: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a" }
];

export const products: Product[] = [
  {
    id: "P1001",
    slug: "premium-wireless-earbuds",
    name: "Premium Wireless Earbuds",
    category: "Tech & Gadgets",
    brand: "VY Audio",
    price: 2499,
    originalPrice: 3200,
    rating: 4.6,
    reviews: 143,
    stock: 38,
    badge: "TRENDING",
    featured: true,
    trending: true,
    tags: ["earbuds", "wireless", "bluetooth", "gaming"],
    colors: ["Black", "White"],
    description: "Rich bass, clear call quality and up to 28 hours total playback with compact charging case.",
    specs: { Connectivity: "Bluetooth 5.3", Battery: "28h total", Charging: "USB-C fast charge", Warranty: "6 months supplier warranty" },
    image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46",
    gallery: [
      "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46",
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df"
    ]
  },
  {
    id: "P1002",
    slug: "urban-sneaker-pro",
    name: "Urban Sneaker Pro",
    category: "Footwear",
    brand: "AeroStride",
    price: 3899,
    originalPrice: 5200,
    rating: 4.5,
    reviews: 98,
    stock: 20,
    badge: "BEST SELLER",
    featured: true,
    tags: ["sneakers", "shoes", "urban", "casual"],
    colors: ["Black", "Gray", "White"],
    sizes: ["39", "40", "41", "42", "43"],
    description: "Lightweight sneaker with all-day cushioning and breathable upper for daily movement.",
    specs: { Material: "Mesh + Rubber", Sole: "Anti-slip", Fit: "Regular", Care: "Dry clean only" },
    image: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06",
    gallery: [
      "https://images.unsplash.com/photo-1511556532299-8f662fc26c06",
      "https://images.unsplash.com/photo-1543508282-6319a3e2621f"
    ]
  },
  {
    id: "P1003",
    slug: "classic-metal-watch",
    name: "Classic Metal Watch",
    category: "Watches",
    brand: "VY Time",
    price: 2999,
    originalPrice: 4200,
    rating: 4.4,
    reviews: 54,
    stock: 16,
    newArrival: true,
    badge: "NEW",
    tags: ["watch", "analog", "metal"],
    colors: ["Silver", "Black"],
    description: "Elegant metal strap watch with minimal dial design for premium daily wear.",
    specs: { Movement: "Quartz", WaterResistance: "3 ATM", Strap: "Stainless Steel" },
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314",
    gallery: [
      "https://images.unsplash.com/photo-1524592094714-0f0654e20314",
      "https://images.unsplash.com/photo-1523170335258-f5ed11844a49"
    ]
  },
  {
    id: "P1004",
    slug: "fast-charge-adapter-65w",
    name: "65W Fast Charge Adapter",
    category: "Mobile Accessories",
    brand: "VoltEdge",
    price: 1799,
    originalPrice: 2300,
    rating: 4.3,
    reviews: 77,
    stock: 45,
    featured: true,
    tags: ["charger", "usb-c", "fast charge"],
    colors: ["White"],
    description: "Compact charger supporting fast charging for phones, earbuds and tablets.",
    specs: { Power: "65W", Ports: "USB-C + USB-A", Safety: "Over-voltage protection" },
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0",
    gallery: ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0"]
  },
  {
    id: "P1005",
    slug: "minimal-travel-backpack",
    name: "Minimal Travel Backpack",
    category: "Bags",
    brand: "CarryLab",
    price: 2799,
    originalPrice: 3500,
    rating: 4.7,
    reviews: 112,
    stock: 25,
    trending: true,
    badge: "TRENDING",
    tags: ["backpack", "travel", "bag"],
    colors: ["Black", "Olive"],
    description: "Water-resistant backpack with multi-compartment layout and laptop sleeve.",
    specs: { Capacity: "26L", Material: "Water-resistant polyester", Laptop: "Up to 15.6 inch" },
    image: "https://images.unsplash.com/photo-1491637639811-60e2756cc1c7",
    gallery: ["https://images.unsplash.com/photo-1491637639811-60e2756cc1c7"]
  },
  {
    id: "P1006",
    slug: "oversized-premium-tee",
    name: "Oversized Premium Tee",
    category: "Fashion",
    brand: "VY Apparel",
    price: 1399,
    originalPrice: 1800,
    rating: 4.4,
    reviews: 66,
    stock: 60,
    newArrival: true,
    badge: "SALE",
    tags: ["t-shirt", "fashion", "oversized"],
    colors: ["Black", "White", "Beige"],
    sizes: ["S", "M", "L", "XL"],
    description: "Soft premium cotton t-shirt with relaxed silhouette and clean streetwear fit.",
    specs: { Fabric: "240 GSM cotton", Fit: "Oversized", Care: "Machine wash cold" },
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab",
    gallery: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab"]
  },
  {
    id: "P1007",
    slug: "polarized-sunglasses-eclipse",
    name: "Eclipse Polarized Sunglasses",
    category: "Accessories",
    brand: "Lensory",
    price: 1599,
    originalPrice: 2300,
    rating: 4.2,
    reviews: 33,
    stock: 18,
    tags: ["sunglasses", "uv", "accessories"],
    colors: ["Black", "Brown"],
    description: "UV400 polarized sunglasses with lightweight frame and premium finish.",
    specs: { UV: "UV400", Frame: "TR90", Lens: "Polarized" },
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083",
    gallery: ["https://images.unsplash.com/photo-1511499767150-a48a237f0083"]
  },
  {
    id: "P1008",
    slug: "portable-bluetooth-speaker-mini",
    name: "Portable Bluetooth Speaker Mini",
    category: "Tech & Gadgets",
    brand: "VY Audio",
    price: 2199,
    originalPrice: 2800,
    rating: 4.5,
    reviews: 84,
    stock: 0,
    badge: "OUT OF STOCK",
    tags: ["speaker", "bluetooth", "portable"],
    colors: ["Black", "Blue"],
    description: "Pocket-size speaker with punchy sound and durable build for travel use.",
    specs: { Playback: "12h", Rating: "IPX5", Connectivity: "Bluetooth 5.2" },
    image: "https://images.unsplash.com/photo-1589003077984-894e133dabab",
    gallery: ["https://images.unsplash.com/photo-1589003077984-894e133dabab"]
  }
];

export const supportedPlatforms = ["Amazon India", "Flipkart", "Myntra", "Meesho", "Ajio", "Tata CLiQ"];

export const orderTimeline = [
  "Order Placed",
  "Payment Confirmed",
  "Product Processing",
  "Product Sourced",
  "In Transit",
  "Arrived in Nepal",
  "Out for Delivery",
  "Delivered"
];
